# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class FieldType(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'FieldType': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['FieldType']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'FieldType']]: ...
    FT_DEFAULT = typing___cast('FieldType', 0)
    FT_CALLBACK = typing___cast('FieldType', 1)
    FT_POINTER = typing___cast('FieldType', 4)
    FT_STATIC = typing___cast('FieldType', 2)
    FT_IGNORE = typing___cast('FieldType', 3)
    FT_INLINE = typing___cast('FieldType', 5)
FT_DEFAULT = typing___cast('FieldType', 0)
FT_CALLBACK = typing___cast('FieldType', 1)
FT_POINTER = typing___cast('FieldType', 4)
FT_STATIC = typing___cast('FieldType', 2)
FT_IGNORE = typing___cast('FieldType', 3)
FT_INLINE = typing___cast('FieldType', 5)

class IntSize(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'IntSize': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['IntSize']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'IntSize']]: ...
    IS_DEFAULT = typing___cast('IntSize', 0)
    IS_8 = typing___cast('IntSize', 8)
    IS_16 = typing___cast('IntSize', 16)
    IS_32 = typing___cast('IntSize', 32)
    IS_64 = typing___cast('IntSize', 64)
IS_DEFAULT = typing___cast('IntSize', 0)
IS_8 = typing___cast('IntSize', 8)
IS_16 = typing___cast('IntSize', 16)
IS_32 = typing___cast('IntSize', 32)
IS_64 = typing___cast('IntSize', 64)

class TypenameMangling(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'TypenameMangling': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['TypenameMangling']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'TypenameMangling']]: ...
    M_NONE = typing___cast('TypenameMangling', 0)
    M_STRIP_PACKAGE = typing___cast('TypenameMangling', 1)
    M_FLATTEN = typing___cast('TypenameMangling', 2)
M_NONE = typing___cast('TypenameMangling', 0)
M_STRIP_PACKAGE = typing___cast('TypenameMangling', 1)
M_FLATTEN = typing___cast('TypenameMangling', 2)

class NanoPBOptions(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    max_size = ... # type: builtin___int
    max_length = ... # type: builtin___int
    max_count = ... # type: builtin___int
    int_size = ... # type: IntSize
    type = ... # type: FieldType
    long_names = ... # type: builtin___bool
    packed_struct = ... # type: builtin___bool
    packed_enum = ... # type: builtin___bool
    skip_message = ... # type: builtin___bool
    no_unions = ... # type: builtin___bool
    msgid = ... # type: builtin___int
    anonymous_oneof = ... # type: builtin___bool
    proto3 = ... # type: builtin___bool
    enum_to_string = ... # type: builtin___bool
    fixed_length = ... # type: builtin___bool
    fixed_count = ... # type: builtin___bool
    mangle_names = ... # type: TypenameMangling

    def __init__(self,
        *,
        max_size : typing___Optional[builtin___int] = None,
        max_length : typing___Optional[builtin___int] = None,
        max_count : typing___Optional[builtin___int] = None,
        int_size : typing___Optional[IntSize] = None,
        type : typing___Optional[FieldType] = None,
        long_names : typing___Optional[builtin___bool] = None,
        packed_struct : typing___Optional[builtin___bool] = None,
        packed_enum : typing___Optional[builtin___bool] = None,
        skip_message : typing___Optional[builtin___bool] = None,
        no_unions : typing___Optional[builtin___bool] = None,
        msgid : typing___Optional[builtin___int] = None,
        anonymous_oneof : typing___Optional[builtin___bool] = None,
        proto3 : typing___Optional[builtin___bool] = None,
        enum_to_string : typing___Optional[builtin___bool] = None,
        fixed_length : typing___Optional[builtin___bool] = None,
        fixed_count : typing___Optional[builtin___bool] = None,
        mangle_names : typing___Optional[TypenameMangling] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> NanoPBOptions: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"anonymous_oneof",u"enum_to_string",u"fixed_count",u"fixed_length",u"int_size",u"long_names",u"mangle_names",u"max_count",u"max_length",u"max_size",u"msgid",u"no_unions",u"packed_enum",u"packed_struct",u"proto3",u"skip_message",u"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"anonymous_oneof",u"enum_to_string",u"fixed_count",u"fixed_length",u"int_size",u"long_names",u"mangle_names",u"max_count",u"max_length",u"max_size",u"msgid",u"no_unions",u"packed_enum",u"packed_struct",u"proto3",u"skip_message",u"type"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"anonymous_oneof",b"anonymous_oneof",u"enum_to_string",b"enum_to_string",u"fixed_count",b"fixed_count",u"fixed_length",b"fixed_length",u"int_size",b"int_size",u"long_names",b"long_names",u"mangle_names",b"mangle_names",u"max_count",b"max_count",u"max_length",b"max_length",u"max_size",b"max_size",u"msgid",b"msgid",u"no_unions",b"no_unions",u"packed_enum",b"packed_enum",u"packed_struct",b"packed_struct",u"proto3",b"proto3",u"skip_message",b"skip_message",u"type",b"type"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"anonymous_oneof",b"anonymous_oneof",u"enum_to_string",b"enum_to_string",u"fixed_count",b"fixed_count",u"fixed_length",b"fixed_length",u"int_size",b"int_size",u"long_names",b"long_names",u"mangle_names",b"mangle_names",u"max_count",b"max_count",u"max_length",b"max_length",u"max_size",b"max_size",u"msgid",b"msgid",u"no_unions",b"no_unions",u"packed_enum",b"packed_enum",u"packed_struct",b"packed_struct",u"proto3",b"proto3",u"skip_message",b"skip_message",u"type",b"type"]) -> None: ...

nanopb_fileopt = ... # type: google___protobuf___descriptor___FieldDescriptor

nanopb_msgopt = ... # type: google___protobuf___descriptor___FieldDescriptor

nanopb_enumopt = ... # type: google___protobuf___descriptor___FieldDescriptor

nanopb = ... # type: google___protobuf___descriptor___FieldDescriptor
