# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oven.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import oven.nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oven.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\noven.proto\x1a\x0cnanopb.proto\"\x1f\n\tSetTarget\x12\x12\n\ntargetTemp\x18\x01 \x01(\x02\")\n\x0bReflowPoint\x12\x0c\n\x04time\x18\x01 \x02(\x03\x12\x0c\n\x04temp\x18\x02 \x02(\x02\"9\n\x0bReflowCurve\x12*\n\x0creflowPoints\x18\x01 \x03(\x0b\x32\x0c.ReflowPointB\x06\x92?\x03\x10\xac\x02\"*\n\x07PIDTune\x12\t\n\x01p\x18\x01 \x01(\x02\x12\t\n\x01i\x18\x02 \x01(\x02\x12\t\n\x01\x64\x18\x03 \x01(\x02\"Q\n\x11OvenConfiguration\x12\x19\n\x07pidTune\x18\x03 \x01(\x0b\x32\x08.PIDTune\x12!\n\x0breflowCurve\x18\x04 \x01(\x0b\x32\x0c.ReflowCurve\"{\n\nOvenStatus\x12\x10\n\x08ovenTemp\x18\x01 \x01(\x02\x12\x13\n\x0b\x61mbientTemp\x18\x02 \x01(\x02\x12\x12\n\ntargetTemp\x18\x03 \x01(\x02\x12\x1d\n\tovenState\x18\x04 \x01(\x0e\x32\n.OvenState\x12\x13\n\x0boutputPower\x18\x05 \x01(\x05\"l\n\x07TxMicro\x12\x11\n\ttimeStamp\x18\x01 \x01(\x03\x12\x1f\n\novenStatus\x18\x02 \x01(\x0b\x32\x0b.OvenStatus\x12-\n\x11ovenConfiguration\x18\x03 \x01(\x0b\x32\x12.OvenConfiguration\"s\n\x07RxMicro\x12\x1a\n\x06target\x18\x01 \x01(\x0b\x32\n.SetTarget\x12\x1d\n\tovenState\x18\x02 \x01(\x0e\x32\n.OvenState\x12-\n\x11ovenConfiguration\x18\x03 \x01(\x0b\x32\x12.OvenConfiguration*4\n\tOvenState\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x12\x0b\n\x07PROFILE\x10\x03\x12\t\n\x05\x45RROR\x10\x04')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_OVENSTATE = _descriptor.EnumDescriptor(
  name='OvenState',
  full_name='OvenState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFILE', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=642,
  serialized_end=694,
)
_sym_db.RegisterEnumDescriptor(_OVENSTATE)

OvenState = enum_type_wrapper.EnumTypeWrapper(_OVENSTATE)
OFF = 0
ON = 1
PROFILE = 3
ERROR = 4



_SETTARGET = _descriptor.Descriptor(
  name='SetTarget',
  full_name='SetTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targetTemp', full_name='SetTarget.targetTemp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_REFLOWPOINT = _descriptor.Descriptor(
  name='ReflowPoint',
  full_name='ReflowPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ReflowPoint.time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='ReflowPoint.temp', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=102,
)


_REFLOWCURVE = _descriptor.Descriptor(
  name='ReflowCurve',
  full_name='ReflowCurve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reflowPoints', full_name='ReflowCurve.reflowPoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\003\020\254\002'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=161,
)


_PIDTUNE = _descriptor.Descriptor(
  name='PIDTune',
  full_name='PIDTune',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='PIDTune.p', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='PIDTune.i', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='PIDTune.d', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=205,
)


_OVENCONFIGURATION = _descriptor.Descriptor(
  name='OvenConfiguration',
  full_name='OvenConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pidTune', full_name='OvenConfiguration.pidTune', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reflowCurve', full_name='OvenConfiguration.reflowCurve', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=288,
)


_OVENSTATUS = _descriptor.Descriptor(
  name='OvenStatus',
  full_name='OvenStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ovenTemp', full_name='OvenStatus.ovenTemp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ambientTemp', full_name='OvenStatus.ambientTemp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetTemp', full_name='OvenStatus.targetTemp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ovenState', full_name='OvenStatus.ovenState', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputPower', full_name='OvenStatus.outputPower', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=413,
)


_TXMICRO = _descriptor.Descriptor(
  name='TxMicro',
  full_name='TxMicro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='TxMicro.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ovenStatus', full_name='TxMicro.ovenStatus', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ovenConfiguration', full_name='TxMicro.ovenConfiguration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=523,
)


_RXMICRO = _descriptor.Descriptor(
  name='RxMicro',
  full_name='RxMicro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='RxMicro.target', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ovenState', full_name='RxMicro.ovenState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ovenConfiguration', full_name='RxMicro.ovenConfiguration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=640,
)

_REFLOWCURVE.fields_by_name['reflowPoints'].message_type = _REFLOWPOINT
_OVENCONFIGURATION.fields_by_name['pidTune'].message_type = _PIDTUNE
_OVENCONFIGURATION.fields_by_name['reflowCurve'].message_type = _REFLOWCURVE
_OVENSTATUS.fields_by_name['ovenState'].enum_type = _OVENSTATE
_TXMICRO.fields_by_name['ovenStatus'].message_type = _OVENSTATUS
_TXMICRO.fields_by_name['ovenConfiguration'].message_type = _OVENCONFIGURATION
_RXMICRO.fields_by_name['target'].message_type = _SETTARGET
_RXMICRO.fields_by_name['ovenState'].enum_type = _OVENSTATE
_RXMICRO.fields_by_name['ovenConfiguration'].message_type = _OVENCONFIGURATION
DESCRIPTOR.message_types_by_name['SetTarget'] = _SETTARGET
DESCRIPTOR.message_types_by_name['ReflowPoint'] = _REFLOWPOINT
DESCRIPTOR.message_types_by_name['ReflowCurve'] = _REFLOWCURVE
DESCRIPTOR.message_types_by_name['PIDTune'] = _PIDTUNE
DESCRIPTOR.message_types_by_name['OvenConfiguration'] = _OVENCONFIGURATION
DESCRIPTOR.message_types_by_name['OvenStatus'] = _OVENSTATUS
DESCRIPTOR.message_types_by_name['TxMicro'] = _TXMICRO
DESCRIPTOR.message_types_by_name['RxMicro'] = _RXMICRO
DESCRIPTOR.enum_types_by_name['OvenState'] = _OVENSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetTarget = _reflection.GeneratedProtocolMessageType('SetTarget', (_message.Message,), dict(
  DESCRIPTOR = _SETTARGET,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:SetTarget)
  ))
_sym_db.RegisterMessage(SetTarget)

ReflowPoint = _reflection.GeneratedProtocolMessageType('ReflowPoint', (_message.Message,), dict(
  DESCRIPTOR = _REFLOWPOINT,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:ReflowPoint)
  ))
_sym_db.RegisterMessage(ReflowPoint)

ReflowCurve = _reflection.GeneratedProtocolMessageType('ReflowCurve', (_message.Message,), dict(
  DESCRIPTOR = _REFLOWCURVE,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:ReflowCurve)
  ))
_sym_db.RegisterMessage(ReflowCurve)

PIDTune = _reflection.GeneratedProtocolMessageType('PIDTune', (_message.Message,), dict(
  DESCRIPTOR = _PIDTUNE,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:PIDTune)
  ))
_sym_db.RegisterMessage(PIDTune)

OvenConfiguration = _reflection.GeneratedProtocolMessageType('OvenConfiguration', (_message.Message,), dict(
  DESCRIPTOR = _OVENCONFIGURATION,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:OvenConfiguration)
  ))
_sym_db.RegisterMessage(OvenConfiguration)

OvenStatus = _reflection.GeneratedProtocolMessageType('OvenStatus', (_message.Message,), dict(
  DESCRIPTOR = _OVENSTATUS,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:OvenStatus)
  ))
_sym_db.RegisterMessage(OvenStatus)

TxMicro = _reflection.GeneratedProtocolMessageType('TxMicro', (_message.Message,), dict(
  DESCRIPTOR = _TXMICRO,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:TxMicro)
  ))
_sym_db.RegisterMessage(TxMicro)

RxMicro = _reflection.GeneratedProtocolMessageType('RxMicro', (_message.Message,), dict(
  DESCRIPTOR = _RXMICRO,
  __module__ = 'oven_pb2'
  # @@protoc_insertion_point(class_scope:RxMicro)
  ))
_sym_db.RegisterMessage(RxMicro)


_REFLOWCURVE.fields_by_name['reflowPoints']._options = None
# @@protoc_insertion_point(module_scope)
